### ISSUE TITLE
Candeo dimmer

### ISSUE THREAD

**Issue by digitalface** [ceuk/planning-poker#4]
Just an FYI as I couldn't see any other way of messaging you - regarding your issue with the Candeo dimmer not reporting its 'on' status until the rotary knob is turned I've messaged Candeo and they've said it was an fault with a batch sold on Amazon. I'm sending mine back to them and they're going to replace it so we'll soon see if the issue is fixed.

**Comment by ceuk** [comment]
haha great news, thanks! :D

**Comment by digitalface** [comment]
Forgot about this - yeah they replaced the dimmer and now status works from on/off without rotating the dimmer.
